ALTER TABLE users
    ADD COLUMN banned BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN can_post_reviews BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE users DROP COLUMN rating;

ALTER TABLE quests
    ADD COLUMN is_rating_considered BOOLEAN DEFAULT FALSE,
    ADD COLUMN is_editable BOOLEAN DEFAULT TRUE,
    ADD COLUMN auto_calculated BOOLEAN DEFAULT TRUE;